server:
  port: 80
  servlet:
    context-path: /
    
  # ssl
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/www.devsgroup.ml/keystore.p12
    key-store-password: 
    key-store-type: PKCS12
    key-alias: tomcat
    
    
    
ssoServerPort: 80

ssoDomain: www.devssso.ml


clientDomain: www.devsgroup.ml
#clientDomain: localhost

systemName: DEVS_GROUP

clientSocketProtocol: ws
clientProtocol: http


  
spring:  
  batch:
    job:
      enabled: false
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@qclass.iptime.org:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: bigfinal03
    password: bigfinal03
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

## jpa
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none

## devtools  
  devtools:
    livereload:
      enabled: true
    
    
logging.level:
  root: warn
  org.springframework:
    boot: info
  com.devs.group: debug